// Package openapi embeds the OpenAPI 3 spec generated by go-swagger3
// and exposes an HTTP handler for Swagger UI.
package openapi

import (
	_ "embed"
	"net/http"

	"github.com/parvez3019/go-swagger3/swagger"
)

//go:embed oas.json
var Spec []byte

// Handler serves Swagger UI and the OpenAPI document under /swagger/.
func Handler() http.Handler {
	return swagger.Handler(Spec, swagger.Title("Go Service Template API"))
}
