// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"go-service-template/internal/infrastructure/context"

	mock "github.com/stretchr/testify/mock"
)

// NewIUserHandler creates a new instance of IUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserHandler {
	mock := &IUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IUserHandler is an autogenerated mock type for the IUserHandler type
type IUserHandler struct {
	mock.Mock
}

type IUserHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserHandler) EXPECT() *IUserHandler_Expecter {
	return &IUserHandler_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type IUserHandler
func (_mock *IUserHandler) CreateUser(ctx *context.GinContext) {
	_mock.Called(ctx)
	return
}

// IUserHandler_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type IUserHandler_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx *context.GinContext
func (_e *IUserHandler_Expecter) CreateUser(ctx interface{}) *IUserHandler_CreateUser_Call {
	return &IUserHandler_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx)}
}

func (_c *IUserHandler_CreateUser_Call) Run(run func(ctx *context.GinContext)) *IUserHandler_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *context.GinContext
		if args[0] != nil {
			arg0 = args[0].(*context.GinContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IUserHandler_CreateUser_Call) Return() *IUserHandler_CreateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *IUserHandler_CreateUser_Call) RunAndReturn(run func(ctx *context.GinContext)) *IUserHandler_CreateUser_Call {
	_c.Run(run)
	return _c
}

// FetchUser provides a mock function for the type IUserHandler
func (_mock *IUserHandler) FetchUser(ctx *context.GinContext) {
	_mock.Called(ctx)
	return
}

// IUserHandler_FetchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUser'
type IUserHandler_FetchUser_Call struct {
	*mock.Call
}

// FetchUser is a helper method to define mock.On call
//   - ctx *context.GinContext
func (_e *IUserHandler_Expecter) FetchUser(ctx interface{}) *IUserHandler_FetchUser_Call {
	return &IUserHandler_FetchUser_Call{Call: _e.mock.On("FetchUser", ctx)}
}

func (_c *IUserHandler_FetchUser_Call) Run(run func(ctx *context.GinContext)) *IUserHandler_FetchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *context.GinContext
		if args[0] != nil {
			arg0 = args[0].(*context.GinContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IUserHandler_FetchUser_Call) Return() *IUserHandler_FetchUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *IUserHandler_FetchUser_Call) RunAndReturn(run func(ctx *context.GinContext)) *IUserHandler_FetchUser_Call {
	_c.Run(run)
	return _c
}
